# Generated by Django 5.1 on 2024-08-28 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_user_is_agent_user_is_organisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.agent",
            ),
        ),
    ]
