# Generated by Django 5.1 on 2024-08-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.userprofile",
            ),
            preserve_default=False,
        ),
    ]
