# Generated by Django 5.1 on 2024-08-29 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_alter_customer_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
